apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorio.fullname" . }}
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: factorio
      protocol: UDP
      name: factorio
  selector:
    {{- include "factorio.selectorLabels" . | nindent 4 }}
