apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftp.fullname" . }}-configmap
  labels:
  {{- include "sftp.labels" . | nindent 4 }}
data:
  users.conf: {{ .Values.user.name }}::{{ .Values.user.id }}
